<?php

/*
 * The table of all REST paths.
 * Require this page in RESTServer if you want stuff to work.
 */

const REST_HANDLER_TABLE = array(
    ["path" => "/",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_IndexPage"],

    ["path" => "/home",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_IndexPage"],

    ["path" => "/test",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_Test"],

    ["path" => "/page/comments",
        "method" => "GET",
        "path_len" => 2,
        "min_args" => 0,
        "max_args" => 1,
        "handler" => "Handle_GetPageComments"],

    ["path" => "/page/info",
        "method" => "GET",
        "path_len" => 2,
        "min_args" => 0,
        "max_args" => 1,
        "handler" => "Handle_GetPageUserInfo"],

    ["path" => "/page/vote",
        "method" => "POST",
        "path_len" => 2,
        "min_args" => 0,
        "max_args" => 2,
        "handler" => "Handle_PageVote"],

    ["path" => "/page/comment/new",
        "method" => "POST",
        "path_len" => 3,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_PostPageComment"],

    ["path" => "/comment",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 1,
        "max_args" => 1,
        "handler" => "Handle_Comment"],

    ["path" => "/comment",
        "method" => "PUT",
        "path_len" => 1,
        "min_args" => 1,
        "max_args" => 3,
        "handler" => "Handle_CommentVote"],

    ["path" => "/comment",
        "method" => "POST",
        "path_len" => 1,
        "min_args" => 1,
        "max_args" => 3,
        "handler" => "Handle_CommentEditContent"],

    ["path" => "/comment",
        "method" => "DELETE",
        "path_len" => 1,
        "min_args" => 1,
        "max_args" => 1,
        "handler" => "Handle_CommentDelete"],

    ["path" => "/session/login",
        "method" => "POST",
        "path_len" => 2,
        "min_args" => 0,
        "max_args" => 2,
        "handler" => "Handle_Login"],

    ["path" => "/session/logout",
        "method" => "GET",
        "path_len" => 2,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_Logout"],

    ["path" => "/session/signup",
        "method" => "POST",
        "path_len" => 2,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_Signup"],

    ["path" => "/session/username",
        "method" => "GET",
        "path_len" => 2,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_SessionUserName"],

    ["path" => "/user",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 0,
        "max_args" => 1,
        "handler" => "Handle_SiteUserProfile"],

    ["path" => "/user",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 2,
        "max_args" => 2,
        "handler" => "Handle_SiteUserFollowLists"],

    ["path" => "/user",
        "method" => "POST",
        "path_len" => 1,
        "min_args" => 1,
        "max_args" => 3,
        "handler" => "Handle_UserAction"],

    ["path" => "/notifications/number",
        "method" => "GET",
        "path_len" => 2,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_NotificationNumber"],

    ["path" => "/notifications/pull",
        "method" => "GET",
        "path_len" => 2,
        "min_args" => 0,
        "max_args" =>  0,
        "handler" => "Handle_PullNotifications"],

    ["path" => "/notifications/read",
        "method" => "PUT",
        "path_len" => 2,
        "min_args" => 1,
        "max_args" => 1,
        "handler" => "Handle_ReadNotifications"],

    ["path" => "/site/page/comments",
        "method" => "GET",
        "path_len" => 3,
        "min_args" => 0,
        "max_args" => 9,
        "handler" => "Handle_SitePageComments"],

    ["path" => "/website",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 1,
        "max_args" => 1,
        "handler" => "Handle_SiteSitePage"],

    ["path" => "/hashtag",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 1,
        "max_args" => 1,
        "handler" => "Handle_SiteHashtag"],

    ["path" => "/search",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_SiteSearch"],

    ["path" => "/search/ajax",
        "method" => "GET",
        "path_len" => 2,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_Search"],

    ["path" => "/thread",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 1,
        "max_args" => 1,
        "handler" => "Handle_SiteThread"],

    ["path" => "/about",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_SiteAbout"],

    ["path" => "/privacy",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_SitePrivacyPolicy"],

    ["path" => "/terms",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_SiteTermsPage"],

    ["path" => "/contact",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_SiteContact"],

    ["path" => "/browser-extension",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_SiteExtension"],

    ["path" => "/site/user",
        "method" => "GET",
        "path_len" => 2,
        "min_args" => 0,
        "max_args" => 1,
        "handler" => "Handle_SiteUserProfile"],

    ["path" => "/site/login",
        "method" => "GET",
        "path_len" => 2,
        "min_args" => 0,
        "max_args" => 1,
        "handler" => "Handle_SiteLogin"],

    ["path" => "/site/settings",
        "method" => "GET",
        "path_len" => 2,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_SiteSettings"],

    ["path" => "/site/settings/uploadprofilepicture",
        "method" => "POST",
        "path_len" => 3,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_SiteSettingsUploadProfilePicture"],

    ["path" => "/site/settings/uploadcoverpicture",
        "method" => "POST",
        "path_len" => 3,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_SiteSettingsUploadCoverPicture"],

    ["path" => "/site/settings/updatepassword",
        "method" => "POST",
        "path_len" => 3,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_SiteSettingsUpdatePassword"],

    ["path" => "/site/settings/update",
        "method" => "POST",
        "path_len" => 3,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_SiteSettingsUpdateDetails"],

    ["path" => "/site",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 0,
        "max_args" => 0,
        "handler" => "Handle_IndexPage"],

    ["path" => "/site",
        "method" => "GET",
        "path_len" => 1,
        "min_args" => 1,
        "max_args" => 99,
        "handler" => "Handle_SiteDefault"],
);